stage_1_prompt_template = """
You are a pathologist who has received a pathology report for a patient. This report has been generated by using ocr on a scanned document, so it may contain errors. Your task is to extract information from the report and provide a brief explanation for each choice.
Carefully analyze the following pathology report and extract information for each category. If information is unclear or not present, choose "UNKNOWN". Provide a **brief, evidence-based explanation** for each choice by quoting the report directly.

For each category, provide:
[Category]: [Chosen option]
Explanation: [Brief explanation with direct quotes from the report]

Example:
Pathology Report: "BREAST, NEEDLE LOCALIZED LUMPECTOMY: Invasive ductal carcinoma, high grade. Tumor measures 2.5 cm. Left breast specimen."

Site: "BREAST"
Explanation: "The report states 'BREAST, NEEDLE LOCALIZED LUMPECTOMY'."

Stage: "pT2N0M0"
Explanation: "The report states 'Tumor measures 2.5 cm', which corresponds to pT2. No lymph node involvement is mentioned, so pN0 is assumed. Therefore, the stage is pT2N0M0."

Laterality: "UNKNOWN"
Explanation: "The report does not mention the laterality of the tumor."

Grade: "high grade"
Explanation: "The report mentions 'high grade'."

Histology: "Invasive ductal carcinoma"
Explanation: "The report states 'Invasive ductal carcinoma'."

Behaviour: "UNKNOWN"
Explanation: "The report does not mention the behavior of the tumor."

Pathology Report:
{report}
"""

stage_2_prompt_template = """
You are tasked with reviewing and scoring the accuracy of information extracted from a pathology report. Your goal is to evaluate each category by comparing the AI's extraction with the actual content in the report. Assess whether the extracted values match the report's information, and provide a justification along with a score for each.

For each category, include:
- **AI Extraction**: [Extracted information from Stage 1]
- **Correct Value**: [Actual correct information from the report]
- **Justification**: [Evidence from the report supporting the correct value, with direct quotes]
- **Score**: [1 if correct, 0 if incorrect]
- **Reasoning**: [Explanation on why the extraction is correct or incorrect]

If information is unclear or ambiguous, choose "UNKNOWN" and provide reasoning.

#### Example

**Pathology Report**:  
"BREAST, UPPER INNER QUADRANT, NEEDLE LOCALIZED LUMPECTOMY: Invasive ductal carcinoma, high grade. Tumor measures 2.5 cm. Left breast specimen."

**Categories**:
1. **Site**:  
   - **AI Extraction**: "UPPER INNER QUADRANT"  
   - **Correct Value**: "UPPER INNER QUADRANT"  
   - **Justification**: The report explicitly states "Tumor Site: Upper inner quadrant."  
   - **Score**: 1  
   - **Reasoning**: The extraction is accurate as it directly matches the report’s description.

2. **Stage**:  
   - **AI Extraction**: "pTisN0M0"  
   - **Correct Value**: "pTisN0M0"  
   - **Justification**: The report mentions "pT Category: pTis (DCIS)". No lymph node involvement or metastasis is indicated, supporting pN0M0.  
   - **Score**: 1  
   - **Reasoning**: The extraction matches the TNM classification provided.

3. **Laterality**:  
   - **AI Extraction**: "UNKNOWN"  
   - **Correct Value**: "LEFT"  
   - **Justification**: The report specifies "Left breast specimen."  
   - **Score**: 0  
   - **Reasoning**: The extraction was marked as unknown, but the report explicitly indicates the laterality.

4. **Grade**:
    - **AI Extraction**: "high grade"  
    - **Correct Value**: "high grade"  
    - **Justification**: The report states "high grade."  
    - **Score**: 1  
    - **Reasoning**: The extraction matches the report's description.

5. **Histology**:
   - **AI Extraction**: "Invasive ductal carcinoma"
   - **Correct Value**: "Invasive ductal carcinoma"
   - **Justification**: The report mentions "Invasive ductal carcinoma."
   - **Score**: 1
   - **Reasoning**: The extraction is correct as it directly matches the report's description.

6. **Behaviour**:
   - **AI Extraction**: "UNKNOWN"
   - **Correct Value**: "UNKNOWN"
   - **Justification**: The report does not specify the behavior.
   - **Score**: 1
   - **Reasoning**: The extraction is marked as unknown, which is accurate based on the report.

**Pathology Report**:
{report}

**Here is the extracted information from Stage 1**:
{stage_1_output}
"""

stage_3_prompt_template = """
You have completed two stages of extraction and evaluation of information from a pathology report. 
Now, you are tasked with summarizing the final selections based on the outputs from both stages. 
Your output should be a structured JSON object that includes each extracted category, the final selected value, and the corresponding evaluation score.

Follow this template, filling in the "?" with the appropriate values:
```json
{{
   "site": "?",
   "site_score": "?",
   "stage": "?",
   "stage_score": "?",
   "laterality": "?",
   "laterality_score": "?",
   "grade": "?",
   "grade_score": "?""
   "histology": "?",
   "histology_score": "?",
   "behaviour": "?",
   "behaviour_score": "?"
}}
```

Instructions:

For each category (site, stage, laterality, grade, histology, behaviour), select the final value based on the Stage 1 extraction and Stage 2 evaluation.
Use the scores from Stage 2 evaluation to fill in the score fields for each category.
Ensure that each JSON key is filled with the correct final value and corresponding score.
Use the Stage 1 and Stage 2 outputs provided below to populate each field accurately.

Stage 1 Output: {stage_1_output}

Stage 2 Evaluation: {stage_2_output} 
"""
